### ISSUE TITLE
Account Message Box Task 5

### ISSUE THREAD

**Issue by sharstream** [sharstream/sf_app#6]
The message box will display the name of the account based on the name of the account you click on the table.
Also, the row for the selected account will have a different color.

**Comment by sharstream** [comment]
![image](https://cloud.githubusercontent.com/assets/6071127/13732083/6c4bd5f6-e950-11e5-91a2-ba30da0fc2d5.png)

**Comment by abbcoe** [comment]
Hey David.  I'll give you a few hints. You will need a css script and you will include some javascript methods in the visualforce page to make this work.
