### ISSUE TITLE
Support Order Manual Cloning Enhancement

### ISSUE THREAD

**Issue by abbcoe** [sharstream/sf_app#78]
Modify Support Order Manual Cloning Code to support the new escalation floor field.

**Comment by abbcoe** [comment]
Add escalation floor to support order manual cloning 
![3-30-2016 8-27-55 pm](https://cloud.githubusercontent.com/assets/17522344/14162056/8f0c7474-f6b6-11e5-938d-fb60ed7b8039.jpg)

**Comment by sharstream** [comment]
@cloudbust I had been tried to change both Controller and page file of Support Order Manual Clone. I will report to you from the feature branch just to show you the subversion control process.

**Comment by sharstream** [comment]
![image](https://cloud.githubusercontent.com/assets/6071127/14262053/97026674-fa81-11e5-8609-90b6288754f0.png)

**Comment by sharstream** [comment]
![image](https://cloud.githubusercontent.com/assets/6071127/14262651/9b3034bc-fa84-11e5-85fb-916e56d22975.png)

**Comment by sharstream** [comment]
![image](https://cloud.githubusercontent.com/assets/6071127/14262687/b60bc486-fa84-11e5-8512-f8b9c412555a.png)

**Comment by sharstream** [comment]
@cloudbust Escalation Floor Clone Button is done!
