### ISSUE TITLE
Assign a Permission Set to SOW Summary Section

### ISSUE THREAD

**Issue by sharstream** [sharstream/sf_app#79]
To access to Custom SOW Summary Section PSA Financial Force Users

**Comment by rippersnapper** [comment]
Update this permission set with access of incoming users to Financial Force.
![image](https://cloud.githubusercontent.com/assets/17522344/14193811/1f493fa8-f776-11e5-916d-5cc4e26be9ea.png)

**Comment by abbcoe** [comment]
![image](https://cloud.githubusercontent.com/assets/17522344/14210921/3e88c02c-f7f9-11e5-8ea7-d0c983c84cb7.png)
